id: P007991
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9298
  title: གདམས་ངག་མཛོད་ཀྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    3ea2766394084ee292b70b5c2e5ab23f:
      image_group_id: I1KG9386
      title: ''
      volume_number: 1
      total_pages: 198
ebook_metadata:
  title: གདམས་ངག་མཛོད་ཀྱི་ཟིན་ཐོ།
  author: ''
  sku: P007991
  cover: cover.jpg
  layers:
  - pagination
