id: P007991
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:46.289749
source_metadata:
  id: bdr:W1KG9298
  title: གདམས་ངག་མཛོད་ཀྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    daac81ab1fa448a89f2505646c5bc6c2:
      image_group_id: I1KG9386
      title: Volume 1 of gdams ngag mdzod notes
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
