id: I45929FF0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:39:55+00:00'
last_modified: '2022-06-09T08:23:46.563180+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9298
  title: གདམས་ངག་མཛོད་ཀྱི་ཟིན་ཐོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    4EA6:
      image_group_id: I1KG9386
      title: Volume 1 of gdams ngag mdzod notes
      total_pages: 198
      order: 1
      base_file: 4EA6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
